# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integration tests"

on:
  workflow_call:
    inputs:
      ref:
        description: 'phpstan/phpstan ref to checkout'
        required: true
        type: string
      phar-checksum:
        description: 'PHAR checksum from reproducible build (please rebase)'
        required: true
        type: string

jobs:
  check-phar-checksum:
    name: "Check PHAR checksum"
    runs-on: "ubuntu-latest"
    outputs:
      checksum-result: ${{ steps.checksum-difference.outputs.result }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          repository: "phpstan/phpstan"
          ref: ${{ inputs.ref }}
      - name: "Check PHAR checksum"
        id: checksum-difference
        run: |
          checksum=${{ inputs.phar-checksum }}
          if [[ $(head -n 1 .phar-checksum) != "$checksum" ]]; then
            echo "::set-output name=result::different
          else
            echo "::set-output name=result::same
          fi

  integration-tests:
    name: "Integration Tests"

    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    needs: check-phar-checksum
    if: "needs.check-phar-checksum.outputs.checksum-result == 'different'"

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.1
            script: |
              git clone https://github.com/rectorphp/rector-src.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 303ecc342da1484619c4f875ad67850feeb4b52b
              cp ../rector-composer.lock composer.lock
              composer install
              ../../../phpstan.phar analyse -c ../rector.neon
          - php-version: 8.0
            script: |
              git clone https://github.com/sebastianbergmann/phpunit.git -b 9.5.12 --depth 1 e2e/integration/repo
              cd e2e/integration/repo
              export COMPOSER_ROOT_VERSION=9.5.12
              composer install
              ../../../phpstan.phar analyse -l 8 -c ../phpunit.neon src tests
          - php-version: 8.0
            script: |
              git clone https://github.com/pmmp/PocketMine-MP.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout e0b07ff3087b652407439a29c941f3b66ca92c86
              composer install --ignore-platform-reqs
              ../../../phpstan.phar analyse -c ../pocketmine.neon --memory-limit=2G
          - php-version: 8.0
            script: |
              git clone https://github.com/laravel/framework.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout ceadf6ea68c5ef316abfc618879f2cf9290e45b3
              composer install
              ../../../phpstan.phar analyse
          - php-version: 8.1
            script: |
              git clone https://github.com/Roave/BetterReflection.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 50970c323d45c6b69d20eb620e03980374aac3dd
              composer install
              ../../../phpstan.phar
          - php-version: 8.1
            script: |
              git clone https://github.com/composer/composer.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 9a69c12a0799d5a974f5ec5d2e78be3495b0b06c
              composer install
              composer config platform --unset && composer update
              vendor/bin/simple-phpunit --filter NO_TEST_JUST_AUTOLOAD_THANKS
              ../../../phpstan.phar analyse -c ../composer.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/nextras/orm.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 4edfc4957494ec272899a8916f3f245c59c86d05
              composer install
              ../../../phpstan.phar analyse -c ../nextras.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/slevomat/coding-standard.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 8c49f8e6e4e3661ee6e568a06676146475f73430
              composer install
              ../../../phpstan.phar analyse -c ../slevomat-cs.neon -l 7 SlevomatCodingStandard
              ../../../phpstan.phar analyse -c build/PHPStan/phpstan.tests.neon -l 7 tests
          - php-version: 8.1
            script: |
              git clone https://github.com/ondrejmirtes/orocrm-phpstan-bugreport.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 0d429b658a6e7baff863b6f23f5e6fa35c88d6e7
              composer install
              ../../../phpstan
          - php-version: 8.1
            script: |
              git clone https://github.com/ondrejmirtes/phpstan-magento-testcase.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout f5d8c215569fe5dd22f7236795a353002c0ae58a
              composer install
              ../../../phpstan analyse -c ../magento-testcase.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/symplify/symplify.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 1bc2ca86613da4d86198d3ca33a2d76805daf568
              cp ../symplify-composer.lock composer.lock
              composer install
              ../../../phpstan analyse -c ../symplify.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/nunomaduro/larastan.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout f72a8b1dfaa2eeaf746a93b3257591090c668794
              composer install
              ../../../phpstan.phar analyse -c ../larastan.neon
          - php-version: 7.4
            script: |
              git clone https://github.com/bitExpert/phpstan-magento.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout f845cd4dbdc49d2e005ec2646176ddfcf7d55d38
              composer install
              ../../../phpstan.phar analyse -c ../magento.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/PrestaShop/PrestaShop.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 6c3797271697278b31e2bd0905d54cea6131d335
              composer install
              ../../../phpstan.phar analyse -c ../prestashop.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/doctrine/orm.git -b 2.13.1 --depth 1 e2e/integration/repo
              cd e2e/integration/repo
              composer install
              ../../../phpstan.phar analyse -c ../doctrine-orm.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/doctrine/collections.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 5d08702084fed4ed71e74ec04a736071c581471c
              composer install
              ../../../phpstan.phar
          - php-version: 8.1
            script: |
              git clone https://github.com/doctrine/dbal.git -b 3.4.3 --depth 1 e2e/integration/repo
              cd e2e/integration/repo
              composer install
              ../../../phpstan.phar
          - php-version: 8.1
            script: |
              git clone https://github.com/doctrine/common.git -b 3.4.0 --depth 1 e2e/integration/repo
              cd e2e/integration/repo
              composer install
              ../../../phpstan.phar
          - php-version: 8.1
            script: |
              git clone https://github.com/doctrine/persistence.git -b 3.0.3 --depth 1 e2e/integration/repo
              cd e2e/integration/repo
              composer install
              ../../../phpstan.phar analyse -c ../doctrine-persistence.neon
          - php-version: 8.1
            script: |
              git clone https://github.com/shipmonk-rnd/phpstan-rules.git -b 1.1.1 --depth 1 e2e/integration/repo
              cd e2e/integration/repo
              composer install
              cp ../../../phpstan.phar vendor/phpstan/phpstan/phpstan.phar
              cp ../../../phpstan vendor/phpstan/phpstan/phpstan
              cp ../../../bootstrap.php vendor/phpstan/phpstan/bootstrap.php
              ../../../phpstan.phar && vendor/bin/phpunit tests
          #- php-version: 8.1
          #  script: |
          #    git clone https://git.drupalcode.org/project/drupal.git -b 10.0.x --depth 1 e2e/integration/repo
          #    cd e2e/integration/repo
          #    composer install
          #    ../../../phpstan.phar analyse -c core/phpstan.neon.dist

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          repository: "phpstan/phpstan"
          ref: ${{ inputs.ref }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Download phpstan.phar"
        uses: actions/download-artifact@v3
        with:
          name: phar-file

      - name: "Tests"
        run: "${{ matrix.script }}"
